### ISSUE TITLE
ToDo: followsups / extras / ideas #3

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/TZP#169]
### 🔹 Pages I use to keep tabs on a few things

- [SpiderMonkey](https://spidermonkey.dev/)
- [L10N](https://blog.mozilla.org/l10n/)
- [Experimental features](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features) (not always up to date!)

---

### :small_red_triangle_down: ToDo

🔹 perf
* ongoing: reduce fonts in list(s) - see #34

🔹 isVars
- [ ] harden isFF with items from isEngine
- [ ] harden isEngine with items from isEngine
- [ ] harden isOS
- [ ] harden navKeys with knownGood, knownPoison from isEngine

🔹 general: fingerprints, sections, lies
* [ ] general: add overlay popup to show results for each section and overall
* [ ] general: make worker fingerprint global
   * currently there is only the ua and language sections, results are not used anywhere
   * instead all worker data should be a separate global FP which we use after the fact to report lies
      * i.e we still output a sub-section worker hash (and diffs to doc), but report lies/mismatches in global
* [ ] general: make iframes fingerprint global (same deal as workers above)
* [x] handle passing objects as well as arrays
* don't use `.join()`
   * [ ] don't use `.join()` on arrays for all sDetail data (where we can now use objects or arrays)
   * [ ] don't use `.join()` anywhere else unless we have to (or it is safe)
* [ ] preserve `typeof` where possible
      * e.g. screen metric width/height is a joined string but we already test for NaN
* general: ongoing
   * knownLies (from mathematical proofs etc)
   * apply prototypeLies to metrics
   * logic -> check knownLies -> if no lies then check prototypeLie -> into the section hash data -> into overall hash data
* general: ongoing
   * robust error handling, detection of script blockage: e.g. screen.js needs work

🔹 screen
* [ ] screen: `vw` + `wh` units, visualviewport etc see #29 
* screen: update/add border-snapping subPixel devicePixelRatio PoC to use domrect
* screen: improve android keyboard PoC to use setInterval to detect a static change
* screen: android 73+: see [1514429](https://bugzilla.mozilla.org/1514429):
* screen: android: investigate a history of changes as soon as possible
   - e.g global.js is where I grab initial viewport and window sizes
* screen: android: exploit `font inflation`
* screen: android: exploit position (top/bottom) of toolbar in Fenix [yes, I can detect this]

🔹 ua
* [ ] ua: refactor
   - always return 11 results
   - relax oscpu for specific linux distro strings
   - harden oscpu: win7 vs win8/10 via tiny font check
   - harden userAgent from the other parts: i.e userAgent is constructed using a set method
   - bypass more parts of the userAgent than just version where possible

🔹 feature detection
* [ ] feature detection: new math test for android if isVer is FF68+
   - limit test to only those that cause entropy on android from math research

🔹 language
* [ ] language: add/investigate `NumberFormat v3` [1648137](https://bugzilla.mozilla.org/show_bug.cgi?id=1648137)
* [ ] language: add fractionalSecondDigits etc
   - see [1645107](https://bugzilla.mozilla.org/show_bug.cgi?id=1645107)
   - `https://github.com/tc39/ecma402/pull/347`
* [ ] language: add `Intl.Segmenter` [1423593](https://bugzilla.mozilla.org/show_bug.cgi?id=1423593), [spec](https://tc39.es/proposal-intl-segmenter/)
* [ ] language: add/investigate `Temporal` API [spec](https://tc39.es/proposal-temporal/docs/index.html)
   - article: https://2ality.com/2021/06/temporal-api.html
   - cookbook: https://tc39.es/proposal-temporal/docs/cookbook.html#arithmetic

🔹 storage
* [ ] storage: auto-output estimate as it doesn't need permission
* [ ] storage: finish the tests

🔹 devices
* [ ] devices
* [ ] devices: more pointer tests
   * android: touch tests: `radiusX/Y`, `screenX/Y`, `clientX/Y`
   * pointerid
* devices: enumerate gamepads/vrdisplays
* devices: use precision timing bypasses to estimate cores

🔹 svg
* [ ] svg: such as
   - ExtentOfChar
   - SVGTextContentElement.prototype.getComputedTextLength
   - SVGPathElement.prototype.getTotalLength
   - SVGGeometryElement.getPointAtLength()

🔹 canvas
* [ ] canvas: add offscreenCanvas
* [ ] canvas: add convertToBlob
* [ ] canvas: add `noise` fingerprint (just for toDataURL)
* [ ] canvas: harden RFP random detection - see https://arkenfox.github.io/TZP/tests/canvasrfp.html
* canvas: make isPoint* more complex, multiple paths
* canvas: get size? get number of colors - overkill?
* canvas: add iframe tests (linked to CB's test page instead for now)

🔹 webgl
* [ ] webgl: add properties/parameters: split into `1, 2, experimental` groups and subgroups e.g. affected by `RFP/prefs`
   * split: e.g. minimal mode RFP restrictions in [1217290 FF57+](https://bugzilla.mozilla.org/show_bug.cgi?id=1217290)
* [ ] webgl: add image tests
   - make sure to expand/test on error entropy for readPixels
   - e.g. in VM's which usually block the graphics driver and the error messages can differ
   - make sure error entropy is handled for TB slider and VMs

🔹 audio
* [ ] audio: see #67 
   - expand methods: see https://github.com/arkenfox/TZP/issues/67#issuecomment-896621330
   - detect known lie: see https://github.com/arkenfox/TZP/issues/67#issuecomment-882366270
   - MOAR: see `DynamicsCompressorNode.reduction` - https://github.com/arkenfox/TZP/issues/67#issuecomment-857305813
* audio: android bug? `ac-outputLatency` is always `0` even after two tries
   - see [1612093](https://bugzilla.mozilla.org/show_bug.cgi?id=1612093) as well

🔹 fonts
* [ ] fonts: use transform:scale ? also collect `ToNumber` - see #167 
* [ ] fonts: add more enumeration methods via `[click here]`
   - font face
   - domrect
   - textmetrics
   - svg
* [ ] update win fonts - https://docs.microsoft.com/en-us/typography/fonts/windows_11_font_list
* [ ] update mac fonts
   - now 10.12 is the minimum in ESR91+ we can clean out some old additional fonts
   - add additional big sur (which is rather large)
* [ ] `system-ui` [1226042](https://bugzilla.mozilla.org/show_bug.cgi?id=1226042)
* [ ] unicode support + FP based on code points assigned per script/version
* [ ] emoji support + FP
* [ ] textMetrics: randomness
   - https://gregtatum.com/writing/2021/diacritical-marks/ for combining unicode
   - double char non-matching
   - combine char with preceeding/next char in looped list: triple-variable-char test
   - number of decimal places
   - non 128ths

* fonts: can we do anything with zalgo
   - https://en.wikipedia.org/wiki/Zalgo_text, http://www.eeemo.net/, https://lingojam.com/GlitchTextGenerator
   - interesting: https://gregtatum.com/writing/2021/diacritical-marks/
* fonts: default font-family name for each of serif + san-serif + monospace
* fonts: font versions: Times New Roman, Arial [thru unicode changes per version]
* FYI: fonts: fontfallback: investigate further
   - when document fonts are blocked, the first run misses fonts it picks up on subsequent tests: currently mitigated by doing a 2-font "priming" run: but this is not an elegant solution
* FYI: fonts: graphite: will be slow like woff

🔹 media
* [ ] media: improve audio/video lists
   - reduce list for perf (we only care about FF), add items for entropy
* [ ] media: mediacapabilities FP
   * also see [1461454](https://bugzilla.mozilla.org/show_bug.cgi?id=1461454)
   * https://w3c.github.io/media-capabilities/#security-privacy-considerations
* media: image hash: encoding/decoding FP?

🔹 css
* [ ] css: prefers-contrast notation - [tests](https://bugzilla.mozilla.org/show_bug.cgi?id=1651857), [article](https://hacks.mozilla.org/2020/07/adding-prefers-contrast-to-firefox/)
    - WTF is this [1658780](https://bugzilla.mozilla.org/show_bug.cgi?id=1658780)

🔹 elements
* clientrect
   * [ ] add more methods: BBox, rootBounds etc
* line height
   * [x] loop sizes
   * [x] use clientrect lies to determine fallback method
   * [x] transform scale to perhaps decimal precision: devicePixelRatio may cause entropy
   * [ ] loop by generic-value font-family
* mathml
   * [x] loop sizes
   * [ ] transform:scale() to force decimals
   * [ ] change values collected to use clientrects actual values
      * currently this is using offSetHeight **_differences_**
      * only use offSetHeight differences between Ctrl vs Test to determine if enabled/disabled (because clientrects may be all lies)
      * if enabled, return clientrect values
   * [ ] use multiple mathml divs to measure different mathml things
      * e.g. https://privacycheck.sec.lrz.de/active/fp_ml/fp_ml.html
      * http://eyeasme.com/Joe/MathML/MathML_browser_test.html
* [ ] widgets / form controls

🔹 misc

🔹 other [backburner]
* other: WebRTC
* other: isAdBlocking [also: hash of results]
* other: sanitizing / zombie storage - [prototype](https://arkenfox.github.io/TZP/tests/sanitizing.html)
* other: RFP timing tests
* injecting resource:// css files for app lang leaks

**Comment by abrahamjuliot** [comment]
I'm currently at 140kb and CSS is 157kb 😭.

**Comment by Thorin-Oakenpants** [comment]
@abrahamjuliot OMG - https://bugzilla.mozilla.org/show_bug.cgi?id=1519167#c117  .. anba had to stop at part 99

**Comment by Thorin-Oakenpants** [comment]
well I got my 11.5 yr old PC down to ~210ms (including adding the webgl at around 15ms)

anyway, here's my new rig, current code
- this is running as file:// and then hitting F5 to eliminate noise and get a stable and best case
![suckitbitches](https://github.com/arkenfox/TZP/assets/16656956/e2a4678e-f145-43be-bfc7-394a4d3ddc99)

@abrahamjuliot ... I think I can get down to 50ms . what do you think?

**Comment by abrahamjuliot** [comment]
Nice. Do we lose a lot of entropy with shorter font lists? Maybe that can be cut by half.

**Comment by Thorin-Oakenpants** [comment]
So I just removed a lot of fonts in windows, will check mac later on. I have a win11 desktop rig, with 182/186 fonts tested (everything MS provides incl win11, including all supplemental, and downloads such as 'Cascadia Code','Cascadia Mono') - I do not have 'Arial Unicode MS','MS Reference Specialty','MS Outlook' (which are installed with office or other MS products, IDK about office365) .. not looked at the new office font .. and I don;t have `'AlternateGothic2 BT'` which is in the RFP font vis level 1 for some reason (can't be assed looking up to re-read why jonathan added it, but it's not a MS font AFAICT, but it is in kBaseFonts). The 187th font is a poison pill

So .. I fixed some names up, and it's all peachy.

I had to remove anything that is a "variant" .. black, cond, light, demi, semi, whatever, ultra, etc - because they are not stable. I have an issue open for font variants. Remember when you said you had windows 10/11 sometimes detect Arial Black and sometimes now, or Arial Narrow .. whatever. Well, this seems to be due to some change in windows and/or Firefox. I believe it's due to the OS as FF is stable as fuck on my old machine.

unstable is like this
- start new browser session, first load - it will detect some fonts as their namesake, e.g. it will detect Corbel Light because Corbel is used, and it will record the size as Corbel's, when Corbel Light is actually different. Or it will not detect a font.
- do a refresh and _then_ it becomes stable with all fonts detected and with the correct sizes, i.e actually using the font

So I surmise this has to do with font-weight, and I think all I need to do is, in a new test or wrapped into this one, is break the fonts lists into weights and loop weights, list, font (and record base the same)

Anyway, so fonts dropped from 240 to 190 in windows. But I added an extra char (a tofu) in the test string. The shorter the test string the faster the test (less glyphs to get per font). So perf didn't change much. The font string used in the test doesn't increase detection of fonts, but it increases the bumber of sizes collected

```js
	if ("windows" === os) {
		// Mō = 124 +"á" = 125 +"Ω" = 127 (win7)
		// Mō - 141 +"á" = 142 +"Ω" = 144 | Mō - 141 +tofu = 154 | (win11: have 182/186 fonts
		let tofu = get_fntCodes("tofu")
		fntString = isTB ? "?-"+ tofu : "Mō"+ tofu
```

^ that's `Mō` gave me 141 sizes for 182 fonts, but `Mō`+tofu gave me 154 sizes for 182 fonts

now I have a mac, I'll be doing all that for mac. Linux and android font lists don't have any "variants"

I think fonts sizes may provide entropy (sort of an equivalency of system scaling, subpixels, cleartype, font version maybe), and I test them all because besides the core group they're all supplemental and you can't really leave any out - although I have, see code for why (assumptions, e.g if you have `Segoe UI Variable Display` then you're going to have `Segoe UI Variable Small` and `Segoe UI Variable Text` and they are the same size, etc

With variants, there are so many (I and I will not be testing styles, e.g. italic), I may have to be more selective. But overall, it's up to me to cover as much as possible, or all of it .. so that when we do collect some data, we can see where the entropy is coming from. At least in FF116+ it's limited to Win10+ and macOS 10.16+ (or whatever it was)

**Comment by Thorin-Oakenpants** [comment]
perf
```
                   tofu: fonts:    3 ms |   50 ms | 5/21
         unicode glyphs: fonts:   21 ms |   71 ms
              fontsizes: fonts:   21 ms |   93 ms
```

Looks like it takes about 10 fonts per ms (there's a few ms in that 21 being used for base font sizes, and re-arranging the data into an object etc) .. so 18 or 19ms for 187 fonts. I think I'm going to be adding like 100 variants, so we're not going to save here, unless it's core expected fonts everyone has and data analysis says we don't lose entropy in measurements

**Comment by Thorin-Oakenpants** [comment]
I do have some ideas on how to speed up unicode measurements, maybe - but like fonts, that's an area I'm going to expand
