### ISSUE TITLE
ToDo: followsups / extras / ideas

### ISSUE THREAD

**Issue by Thorin-Oakenpants** [arkenfox/TZP#2]
### 🔹 Pages I use to keep tabs on a few things

- [SpiderMonkey](https://spidermonkey.dev/)
- [L10N](https://blog.mozilla.org/l10n/)
- [Experimental features](https://developer.mozilla.org/en-US/docs/Mozilla/Firefox/Experimental_features) (not always up to date!)

---

### :small_red_triangle_down: ToDo

🔹 perf
* [ ] perf: reduce fonts in list(s) - see #34 

🔹 isVars
- [ ] harden isFF with items from isEngine
- [ ] harden isEngine with items from isEngine
- [ ] harden isOS
- [ ] harden navKeys with knownGood, knownPoison from isEngine

🔹 general: fingerprints, sections, lies
* [ ] general: add overlay popup to show results for each section and overall
* [ ] general: make worker fingerprint global
   * currently there is only the ua and language sections, results are not used anywhere
   * instead all worker data should be a separate global FP which we use after the fact to report lies
      * i.e we still output a sub-section worker hash (and diffs to doc), but report lies/mismatches in global
* [ ] general: make iframes fingerprint global (same deal as workers above)
* [x] handle passing objects as well as arrays
* don't use `.join()`
   * [ ] don't use `.join()` on arrays for all sDetail data (where we can now use objects or arrays)
   * [ ] don't use `.join()` anywhere else unless we have to
* [ ] preserve `typeof` where possible
      * e.g. screen metric width/height is a joined string but we already test for NaN
* general: ongoing
   * knownLies (from mathematical proofs etc)
   * apply prototypeLies to metrics
   * logic -> check knownLies -> if no lies then check prototypeLie -> into the section hash data -> into overall hash data
* general: ongoing
   * robust error handling, detection of script blockage: e.g. screen.js needs work

🔹 screen
* [ ] screen: `vw` + `wh` units, visualviewport etc see #29 
* screen: update/add border-snapping subPixel devicePixelRatio PoC to use domrect
* screen: improve android keyboard PoC to use setInterval to detect a static change
* screen: android 73+: see [1514429](https://bugzilla.mozilla.org/1514429):
* screen: android: investigate a history of changes as soon as possible
   - e.g global.js is where I grab initial viewport and window sizes
* screen: android: exploit `font inflation`
* screen: android: exploit position (top/bottom) of toolbar in Fenix [yes, I can detect this]

🔹 ua
* [ ] ua: finish
   - relax oscpu for specific linux distro strings
   - harden oscpu: win7 vs win8/10 via tiny font check
   - harden userAgent from the other parts: i.e userAgent is constructed using a set method
   - bypass more parts of the userAgent than just version where possible
   - consider only returning userAgent

🔹 feature detection
* [ ] feature detection: new math test for android if isVer is FF68+
   - limit test to only those that cause entropy on android from math research

🔹 language
* [ ] language: add/investigate `NumberFormat v3` [1648137](https://bugzilla.mozilla.org/show_bug.cgi?id=1648137)
* [ ] language: add fractionalSecondDigits etc
   - see [1645107](https://bugzilla.mozilla.org/show_bug.cgi?id=1645107)
   - `https://github.com/tc39/ecma402/pull/347`
* [ ] language: add `Intl.Segmenter` [1423593](https://bugzilla.mozilla.org/show_bug.cgi?id=1423593), [spec](https://tc39.es/proposal-intl-segmenter/)
* [ ] language: add/investigate `Temporal` API [spec](https://tc39.es/proposal-temporal/docs/index.html)
   - article: https://2ality.com/2021/06/temporal-api.html
   - cookbook: https://tc39.es/proposal-temporal/docs/cookbook.html#arithmetic

🔹 storage
* [ ] storage: finish the tests
* [ ] storage: auto-output estimate as it doesn't need permission

🔹 devices
* [ ] devices: more pointer tests
   * android: touch tests: `radiusX/Y`, `screenX/Y`, `clientX/Y`
   * pointerid
* devices: enumerate gamepads/vrdisplays
* devices: use precision timing bypasses to estimate cores

🔹 svg
* [ ] such as
   - ExtentOfChar
   - SVGTextContentElement.prototype.getComputedTextLength
   - SVGPathElement.prototype.getTotalLength
   - SVGGeometryElement.getPointAtLength()

🔹 canvas
* [ ] canvas: add offscreenCanvas
* [ ] canvas: add convertToBlob
* [ ] canvas: add `noise` fingerprint (just for toDataURL)
* [ ] canvas: harden RFP random detection - see https://arkenfox.github.io/TZP/tests/canvasrfp.html
* canvas: make isPoint* more complex, multiple paths
* canvas: get size? get number of colors - overkill?
* canvas: add iframe tests (linked to CB's test page instead for now)

🔹 webgl
* [ ] webgl: add properties/parameters: split into `1, 2, experimental` groups and subgroups e.g. affected by `RFP/prefs`
   * split: e.g. minimal mode RFP restrictions in [1217290 FF57+](https://bugzilla.mozilla.org/show_bug.cgi?id=1217290)
* [ ] webgl: add image tests
   - make sure to expand/test on error entropy for readPixels
   - e.g. in VM's which usually block the graphics driver and the error messages can differ
   - make sure error entropy is handled for TB slider and VMs

🔹 audio
* [ ] audio: see #67 
   - expand methods: see https://github.com/arkenfox/TZP/issues/67#issuecomment-896621330
   - detect known lie: see https://github.com/arkenfox/TZP/issues/67#issuecomment-882366270
   - MOAR: see `DynamicsCompressorNode.reduction` - https://github.com/arkenfox/TZP/issues/67#issuecomment-857305813
* audio: android bug? `ac-outputLatency` is always `0` even after two tries
   - see [1612093](https://bugzilla.mozilla.org/show_bug.cgi?id=1612093) as well

🔹 fonts
* [ ] fonts: textMetrics: randomness
   - https://gregtatum.com/writing/2021/diacritical-marks/ for combining unicode
   - double char non-matching
   - combine char with preceeding/next char in looped list: triple-variable-char test
   - number of decimal places
   - non 128ths
* [ ] update win fonts - https://docs.microsoft.com/en-us/typography/fonts/windows_11_font_list
* [ ] update mac fonts
   - now 10.12 is the minimum in ESR91+ we can clean out some old additional fonts
   - add additional big sur (which is rather large)
* [ ] - `system-ui` [1226042](https://bugzilla.mozilla.org/show_bug.cgi?id=1226042)
* [ ] fonts: enumerate via `[click here]`
   - font face
   - domrect
   - textmetrics
   - svg
   - canvas? is it worth it?
* fonts: can we do anything with zalgo
   - https://en.wikipedia.org/wiki/Zalgo_text, http://www.eeemo.net/, https://lingojam.com/GlitchTextGenerator
   - interesting: https://gregtatum.com/writing/2021/diacritical-marks/
* fonts: default font-family name for each of serif + san-serif + monospace
* fonts: font versions: Times New Roman, Arial [thru unicode changes per version]
* FYI: fonts: fontfallback: investigate further
   - when document fonts are blocked, the first run misses fonts it picks up on subsequent tests: currently mitigated by doing a 2-font "priming" run: but this is not an elegant solution
* FYI: fonts: graphite: will be slow like woff

🔹 media
* [ ] media: improve audio/video lists
   - reduce list for perf (we only care about FF), add items for entropy
* [ ] media: mediacapabilities FP
   * also see [1461454](https://bugzilla.mozilla.org/show_bug.cgi?id=1461454)
   * https://w3c.github.io/media-capabilities/#security-privacy-considerations
* media: image hash: encoding/decoding FP?

🔹 css
* [ ] css: prefers-contrast notation - [tests](https://bugzilla.mozilla.org/show_bug.cgi?id=1651857), [article](https://hacks.mozilla.org/2020/07/adding-prefers-contrast-to-firefox/)
    - WTF is this [1658780](https://bugzilla.mozilla.org/show_bug.cgi?id=1658780)

🔹 elements
* [ ] widgets
* clientrect
   * [ ] add more methods: BBox, rootBounds etc
* line height
   * [x] loop sizes
   * [x] use clientrect lies to determine fallback method
   * [x] transform scale to perhaps decimal precision: devicePixelRatio may cause entropy
   * [ ] loop by generic-value font-family
* mathml
   * [x] loop sizes
   * [ ] transform:scale() to force decimals
   * [ ] change values collected to use clientrects actual values
      * currently this is using offSetHeight **_differences_**
      * only use offSetHeight differences between Ctrl vs Test to determine if enabled/disabled (because clientrects may be all lies)
      * if enabled, return clientrect values
   * [ ] use multiple mathml divs to measure different mathml things
      * e.g. https://privacycheck.sec.lrz.de/active/fp_ml/fp_ml.html
      * http://eyeasme.com/Joe/MathML/MathML_browser_test.html

🔹 misc

🔹 other
* [ ] other: WebRTC
* [ ] other: isAdBlocking [also: hash of results]
* [ ] other: sanitizing / zombie storage - [prototype](https://arkenfox.github.io/TZP/tests/sanitizing.html)
* [ ] other: widgets/form controls
* [ ] other: RFP timing tests
* [ ] other: elements (and injecting resource:// css files for app lang leaks)

🔹 randomizing detection
* random: audio / ~~domrect~~ / ~~measureText~~ (see textMetrics) / ~~canvas~~ (see canvas noise)
* random: ^^ might be useful for css line-height / unicode gylphs

---

### Done :small_red_triangle_down:

🔹 September 2020
* [x] feature detection: math !== TB vs FF, it is `mingw` vs `windows-sdk` in clang
   * change output to reflect this, and don't set isTB on windows when `B`
   * feature detection: fixes `new` branding detection when a FF mingw build thinks it's Tor Browser
* [x] feature detection: v82 detection
* [x] canvas: added noise detection (i.e stealth randomizing) for blink engines
* [x] general
   - section perf is now rounded (and also the performance.now() in misc): I hate the precision in chromium tests
   - section perf is now also displayed in the section title bar (and updated when rerun)
* [x] domrect: various
   - promisify the runs
   - second run added to detect randomness on each pass
   - sha1 now used and perf is now correctly calculated (previously it wasn't waiting for the sha256 crypto)
   - noise detection
      - no longer uses elements that cause false positives in blink
      - is now also applied when `isEngine` = "blink"
      - now checks diffs per method (each method has it's own array)
   - section hash added: results for each method can be
      - the hash
      - `random` (i.e randomness on each pass)
      - `tampered` (i.e stealth randomness)
      - an error name
   - tested with AOPR

🔹 October 2020
* [x] feature detection: v83 detection
* [x] ua: BS detection
   - forgot to list: couldn't be assed keeping two lots of UA functions in my local screen.js, and with all the changes just let it get added
   - this is implausible results based on feature detection and typos/spaces etc
   - incomplete: I need to cover the `navigator.userAgent` string
   - it will cater for RFP (and I can tell if RFP is on)
* [x] devices: plugins, mime types are sorted
   - also FF plugin lies: at most it can only return Flash
* [x] canvas: decide if stability is important
   - changed to match CB test
   - the FP is now stable across FF60-Dev/Beta. It changes in Nightly (always has: must be some pref or hardcoded flag)
   - this now makes the results **zoom-resistant** by setting Arial
   - note: if document fonts are blocked, then the default font (e.g. Times New Roman) can cause the zoom resistance to be lost (depends on what your default font is) - item added to ToDo to look at doing away with factors that unduly influence results

🔹 November 2020
* [x] feature detection: v84 test
* [x] language: add date.parse` multi-year timezone offset calculation PoC
* [x] feature detection: v85 test
* [x] ua: worker/iframe nav checks
   - added iframe tests
   - section hash logic is
      - there is no point collecting a fake/random UA hash as it is not stable (technically a lie isn't either)
      - we use the document hash
      - if an iframe leaks, it leaks completely and we detect the first one and use that instead: iframes have all 11 properties
      - if no iframes leak, we then use worker leaks (yet to promisify and add into logic: note web worker to not be included in logic as userAgent can be spoofed)... workers have 6 properties
      - if no worker leaks then we fall back to the feature detection BS
      - if BS then we return a single "has lied", otherwise, it's the original document hash

🔹 January 2021
* [x] fonts: detect font lies: expanded tests to the creepy suite
   - added: client, scroll, pixel, size, perspective, transform
* [x] devices
   - FF plugins/mimetypes: if isFF then flash only up to and including FF84 _and_ it must be correct in both plugins + mimetypes
   - other plugins: creepy pluginLies
* [x] domrect: expand elements and measurements used to detect lies
* [x] feature detection: v86 test
* [x] known lies collection and output started
* [x] prototype lies collection: big ups to creepy 👍 
* [x] feature detection: v87 test

🔹 February 2021
* [x] domrect: known value PoC for Firefox
   - now catches known lies where the amount added/subtracted is consistent across all elements
* [x] feature detection: v88 test
* [x] feature detection: make error strings tamperproof
   - also in some version tests

🔹 March 2021
* [x] general: important global vars are now promised first, robust, and done once
   - `isFF test 1`:  a triple installTrigger test is run as soon as generic.js lands
   - when all js files have arrived, two more checks isFF checks are promised
      - `isFF test 2`: the error test is 100% wrapped in `newFn()` to prevent tampering
      - `isFF test 3`: a system widget font is read
   - then we promise the next group
      - the first is `isEngine` (which doubles as the`isFF test 4` if the math reveals gecko)
      - and then if isFF = true: we also get isOS, isVer and isTB
   - these global vars are used everywhere, so we want them set before we do anything serious
   - these are only ever done once, on page load
* [x] general: more promises & globals before starting
   - after the all the `isThings` (above), on page-load, global reruns, section re-runs, (and todo: click-here buttons if required), we also promise and set
      - navigator keys: trueKeys, fakeKeys so we can always get truthiness about nav objects
      - prototype lies
      - we do this since the values can change between manual tests/reruns
      - note that the prototype lies is not the same object as the global snapshot one at the top of the page
* [x] general: perf output
   - there are two perf sub sections: `global` (page load, or global rerun) and `click` (anything else: section reruns, click here)
   - each of those has a details link
   - the global one is a one off, the click one accumulates until you do a global rerun
* [x] general: recording detail data
   - the global snapshot is a full test, and now contains the fingerprint and details
   - section reruns are stored separately: the hash and data is already display, but the details are clickable: e.g. `css system fonts` etc
   - I will expand these clickable details: not just fingerprint detail data, but also items like unexpected errors in languages, storage test information, domrect shift diffs analysis
   - Currently these clickable "buttons" just output to console. The plan is to instead pretty output them to an overlay with options to copy or to output to console in various formats

🔹 April, May, June 2021
* [x] general: lie and bypass color coding
```
DONE: lie detection + bypassable
x "global:isFF" various checks
x "global:isEngine" math
x "global:isOS" (one so far)
x "canvas:toDataURL/toBlob", (as long as one is not noisy)
x "css:computed styles", (FF)
x "css:forced-colors:",
x "css:prefers-color-scheme:",
x "css:prefers-reduced-motion:",
x "devices:any-hover:",
x "devices:any-pointer:",
x "devices:hover:",
x "devices:mimeTypes", (FF85+ = none: also Flash check pre 85 in both)
x "devices:plugins", (FF85+ = none: also Flash check pre 85 in both)
x "devices:pointer:",
x "domrect:xxx", (as long as one is not noisy and all non-noisy ones match)
x "fonts:fonts", (as long as we have 4/7 the same)
x "misc:iframe window properties",
x "misc:navigator keys", (FF: post constructor and expectedKeys hardening)
x "misc:performance.mark",
x "screen:color",
X "screen:inner", (needs work, also used to fix viewport scrollbar)
x "screen:screen", (needs work)
x "ua:version", (isRFP: no uaBS and real version does not match; isBrave spaces)

DONE: lie detection: unbypassable
  "fd:math",
  "ua:navigator"

TODO: to color up (from above list)
  "domrect:xxx",
  "screen:color",
  "screen:inner", (needs work, also used to fix viewport scrollbar)
  "screen:screen", (needs work)

TODO:
  "fd:errors": build+show parallel construction (compare to newFn)
  "fd:math": build+show parallel construction (compare to -1, Math.E)  ???
  "screen:devicePixelRatio": isFF PoC: trim to 6 decimal places: compare, allow floating diffs
```

* [x] general: finish promisifying each section
* [x] general: recording of methods: work in progress
* [x] general: use of css pseudo values to bypass matchmedia and nav lies: work in progress
* [x] general: proxy lies - thanks @abrahamjuliot 👍 
* [x] general: hardened isFF, isOS, isEngine
* [x] general: hardened isBrave, isBraveMode - thanks @abrahamjuliot 👍 
* [x] general: hardened navKeys: more to come with known-always-there good keys
* [x] general: hashes are sha1 length, columns aligned better 
* [x] screen: zoom resistance (which I think is impossible for all metrics): on FF desktop, recalc the screen as if at 100%
   - I will probably drop this, and/or split zoom affected metrics into a new fingerprint array
* [x] ua: iframe results create clickable diffs
* [x] feature detection: v89 v90 + v91
* [x] feature detection: OS architecture via large array buffers (and hardened with math results): can only confirm 64bitness
* [x] feature detection: supportedLocales
* [x] feature detection: hardened errors via newFn - thanks @abrahamjuliot 👍 
* [x] language: Extended TimeZoneName
* [x] language: expanded Intl.PluralRules to include cardinal
* [x] language: fixed several formatToParts to get the right parts
* [x] canvas: simplified results, WIP, see #85 
* [x] audio: some basic lie detection
* [x] fonts: use base font list (for windows, so far) if RFP enabled in FF80+ (and not Tor Browser)
   - will expand on this; e.g. for Mac, for specific TB OSes, and can drop even more from the current base list
* [x] fonts: moved unicode glyph fallback delay directly into the html

probably missed some stuff

🔹 last half of 2021
* [x] isFF: eval.toString().length
* [x] isFF: harden triple installtrigger tests by checking type
* [x] feature detection: v92, v93, v94
* [x] feature detection: use supportedLocalesOf in collation to remove variable/unstable results
* [x] feature detection: added RFP math
* [x] feature detection: added canonical locales
* language: add/investigate `Enumeration API` [1670033](https://bugzilla.mozilla.org/show_bug.cgi?id=1670033)
   * doesn't add anything
* language: investigate `getCanonicalLocales`
   * doesn't add anything except engine detection
* [x] language: Intl.Segmenter resolved options
* [x] devices: pointerover
* [x] fonts: reduced font lists: kBaseFonts for FF & isRFP,  TB whitelists if isTB
   * windows: 117 (RFP) 81 (TB) 251 (full)
   * mac: 201 (RFP) 46 (TB) 432 (full)

probably missed some stuff

...

**Comment by Thorin-Oakenpants** [comment]
@abrahamjuliot ... damn... that's secksie fast for my 11yr old PC (admittedly, perf is not always exact: e.g. I need to promisify worker returns in language + ua), and I've yet to add in webgl and some other tests that might take a good chunk of time

load (new session, cache was cleared) is always about 1000
reload (cache being used): varies between 700-800
rerun: varies between 570 (wooo!) and 650'ish

![sweeeeeet](https://user-images.githubusercontent.com/16656956/95814424-e69f5300-0d09-11eb-8447-a5d3d3148a29.png)

Whaddaya think?

**Comment by abrahamjuliot** [comment]
Lookin' good. I get roughly 700-800 on reload and rerun.

**Comment by Thorin-Oakenpants** [comment]
I use Nightly as I prototype: so probably Warp is making it speedier

**Comment by Thorin-Oakenpants** [comment]
@sereneblue https://arkenfox.github.io/TZP/tests/iframes.html (it's a temp test page) .. where I'm dragging in navigator ua properties: seems like Chameleon doesn't cover these (I thought they did)

**Comment by sereneblue** [comment]
@Thorin-Oakenpants Thanks for bringing this up. I'll try to address this in a future update.

**Comment by kkapsner** [comment]
Chameleon fails quite a bit on my test [page](https://canvasblocker.kkapsner.de/test/navigatorTest.php):
![image](https://user-images.githubusercontent.com/1105157/97805201-f64cf000-1c54-11eb-979b-4385d3f1f08b.png)

CB fails at the workers as well - I have not figured out a good way to protect these...

**Comment by Thorin-Oakenpants** [comment]
@kkapsner `sneaky window` and `window.length -1` - are these worth adding to iframes (minus SOP) for TZ's UA upgrade?

**Comment by kkapsner** [comment]
`window.frames` is a different way to access the iframes content windows. It's not worth adding that to TZ.

`sneaky window` is [here](https://github.com/kkapsner/CanvasBlocker/blob/master/test/iframeAPI.js#L58-L70) and is the only one I would bother with... and I think this is exactly what you are doing on your test page.

**Comment by Thorin-Oakenpants** [comment]
@abrahamjuliot .. added to my todo above ... Extended TimeZoneName Options [1710429](https://bugzilla.mozilla.org/show_bug.cgi?id=1710429) [github](https://github.com/tc39/proposal-intl-extend-timezonename)

**Comment by Thorin-Oakenpants** [comment]
There's also https://bugzilla.mozilla.org/show_bug.cgi?id=1693575 (landed) and https://bugzilla.mozilla.org/show_bug.cgi?id=1693576 (not far away)

**Comment by Thorin-Oakenpants** [comment]
@abrahamjuliot : so what your ideas on how to integrate the following
1 Extended TimeZoneName Options
2 not sure there is anything to be gained from DisplayNames - IIRC you have to specify a language, can;t be undefined

1. I guess we use undefined, and then we want to use formatToParts or something to get the TZ strings? Is this even worth it? Is this something extensions need to spoof, or is it handled automagically when they lie about resolved options?

**Comment by abrahamjuliot** [comment]
> Extended TimeZoneName Options

```js
// reduce to object
const timeZoneName = ['short', 'long', 'shortOffset', 'longOffset', 'shortGeneric', 'longGeneric']
.reduce((acc, name) => {
    let timeString = '' // default if not supported
    try {
        timeString = new Date().toLocaleTimeString('en', { timeZoneName: name })
    }
    catch (e) {}
    acc[name] = timeString
    return acc
}, {})

// access properties
timeZoneName.long // returns "2:56:45 PM Pacific Daylight Time"
```

> DisplayNames

If the language is set to an a-z gibberish string, the language display defaults to the system region.

![image](https://user-images.githubusercontent.com/6946045/120942075-4c967b80-c6db-11eb-8d18-5b623a19233a.png)

In this example, using Chrome Sensors, I switched my location to Moscow and then Tokyo. 

![image](https://user-images.githubusercontent.com/6946045/120942036-00e3d200-c6db-11eb-9314-23053639aa3c.png)

> Is this something extensions need to spoof, or is it handled automagically when they lie about resolved options?

Extensions can spoof this. I've only seen Cydec attempt consistency with INTL methods. Here's the [Cydec](https://jsfiddle.net/35L21b7d/) function.

Puppeteer can set the timezone automagically: `https://github.com/puppeteer/puppeteer/issues/3325`

**Comment by Thorin-Oakenpants** [comment]
shouldn't we be using `undefined` and not `en`?

```js
timeString = new Date().toLocaleTimeString('en', { timeZoneName: name })
```

**Comment by abrahamjuliot** [comment]
Yes, I'm adding that above. I use 'abc' since 'undefined' throws an error in chrome.

**Comment by Thorin-Oakenpants** [comment]
Or use a random string :)

**Comment by Thorin-Oakenpants** [comment]
the problem I have with https://github.com/arkenfox/TZP/issues/2#issuecomment-855475106 is that you can't reliably(?) or easily(?) parse the results for just the extended timezoneName

notes:
- loop two dates to get DST names and non-DST names
   - the extended names don't seem to use DST names: may just be some timezones, or it gets hooked up later
   - the two dates do show the time difference in some extended timezones (e.g. 12 vs 13) but TZP already does that
   - the two dates do expose the long names for DTS/non-DST, but TZP already does that by forcing `long` in tests
   - maybe two dates is a waste of time, plus it's limited to the one year
- using undefined
- using formatToParts index [6]
   - would prefer something that checks for type `timeZoneName` but the extended ones are type `unknown`
   - am not sure if index [6] is always the correct item? e.g. what about LTR (left to right?)
- JSON.stringify and clean up the noise

```js
let tzRes = []
try {
	let tzNames = ["short","long","shortOffset","longOffset","shortGeneric","longGeneric"]
	let tzDays = ["January 1, 2019 13:00:00","July 1, 2019 13:00:00"]
	tzDays.forEach(function(day) {
		tzNames.forEach(function(item) {
			let tzString = ""
			let tzDate = new Date(day)
			try {
				let tzO = {hour12: true, timeZoneName: item}
				tzString = JSON.stringify(Intl.DateTimeFormat(undefined, tzO).formatToParts(tzDate)[6])
				tzString = tzString.replace(/"/g, "")
				tzString = tzString.replace("{type:timeZoneName,value:", "")
				tzString = tzString.replace("{type:unknown,value:", "")
				tzString = tzString.replace("}", "")
			} catch(e) {
				//tzString = e.name +": "+ e.message
				if (isVer > 90) {tzString = zB0} else {tzString = zNA} // "blocked" in FF91+ else "not supported"
			}
			tzRes.push(item +":"+ tzString) // temp: add item in result
		})
	})
} catch(e) {
	tzRes = zB0
}
console.log(tzRes)
```

example, `de`
![de](https://user-images.githubusercontent.com/16656956/121772589-c0b2a280-cb65-11eb-8e4b-12d648fa3fec.png)

I'm thinking there must be a cleaner, simpler way to do this - @abrahamjuliot .. back to you

**Comment by Thorin-Oakenpants** [comment]
Looks like cydec hasn't been protecting timezone names at all
- here I am as timezone `America/Los_Angeles` (also known as `Pacific Time (US)`)

![geeze](https://user-images.githubusercontent.com/16656956/122085389-316def00-cdf2-11eb-8a8c-137ee4f84ad6.png)

What is interesting is it is now doing something with `date.parse` and maybe `getTime` (I don't think that was covered before), not that I've even started on reducing the language section to five simple metrics with lies/bypasses etc

![mfcker](https://user-images.githubusercontent.com/16656956/122086569-59118700-cdf3-11eb-8272-6ef4c59cab57.png)

So
- the PoC is `NaNs`?
- but the `timezoneOffset | getTime | Date.parse` value of `-420, -420, -420, -420 | 480, 420, 420, 420 | 480, 420, 420, 420` looks correct?

**Comment by Thorin-Oakenpants** [comment]
grr, confusing myself
- `11729887137c5306bc9c34ff642b5e213143c464` is correct for pacific time
   - cydec destroys my PoC for timezones entropy test probably because I'm using toLocaleString, IDK, don't care
- `480, 420, 420, 420` is the correct result as well
   - so `getTime` and `date.parse` haven't been affected

phew

**Comment by Thorin-Oakenpants** [comment]
index [6] is not going to work, here is Tor Browser `vi` with no en-US spoofing
![vi](https://user-images.githubusercontent.com/16656956/122187000-25c80a00-ce7e-11eb-90fc-bc2462489f6e.png)

**Comment by Thorin-Oakenpants** [comment]
@abrahamjuliot : added a link for temporal API in OP: to save you scrolling ... here it is: https://2ality.com/2021/06/temporal-api.html

**Comment by Thorin-Oakenpants** [comment]
@abrahamjuliot fyi - `system-ui` generic fonts landed  FF92+ [1226042](https://bugzilla.mozilla.org/show_bug.cgi?id=1226042)

**Comment by Thorin-Oakenpants** [comment]
@abrahamjuliot what's this about - https://privacy-test-pages.glitch.me/features/navigator-interface.html
- `https://github.com/duckduckgo/privacy-test-pages/commit/6ca2323691d15ea546c1b972924e3b3027f650e3`

I added [DDG Privacy Essentials](https://addons.mozilla.org/firefox/addon/duckduckgo-for-firefox) but I got nothing - is this some chromium thing?

**Comment by abrahamjuliot** [comment]
I'm guessing it's a chromium thing similar to `navigator.brave`.

**Comment by Thorin-Oakenpants** [comment]
closing - new one at #169
